// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: icon/v1/icon_service.proto

package iconv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Icon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link      string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Uuid      string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Kindof    string `protobuf:"bytes,3,opt,name=kindof,proto3" json:"kindof,omitempty"`
	OwnerUuid string `protobuf:"bytes,4,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
}

func (x *Icon) Reset() {
	*x = Icon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Icon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Icon) ProtoMessage() {}

func (x *Icon) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Icon.ProtoReflect.Descriptor instead.
func (*Icon) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{0}
}

func (x *Icon) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Icon) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Icon) GetKindof() string {
	if x != nil {
		return x.Kindof
	}
	return ""
}

func (x *Icon) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

type GetIconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *GetIconRequest) Reset() {
	*x = GetIconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIconRequest) ProtoMessage() {}

func (x *GetIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIconRequest.ProtoReflect.Descriptor instead.
func (*GetIconRequest) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetIconRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetIconResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Icon *Icon `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (x *GetIconResponse) Reset() {
	*x = GetIconResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIconResponse) ProtoMessage() {}

func (x *GetIconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIconResponse.ProtoReflect.Descriptor instead.
func (*GetIconResponse) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetIconResponse) GetIcon() *Icon {
	if x != nil {
		return x.Icon
	}
	return nil
}

type GetIconsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerUuid string `protobuf:"bytes,1,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
}

func (x *GetIconsRequest) Reset() {
	*x = GetIconsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIconsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIconsRequest) ProtoMessage() {}

func (x *GetIconsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIconsRequest.ProtoReflect.Descriptor instead.
func (*GetIconsRequest) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetIconsRequest) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

type GetIconsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Icons []*Icon `protobuf:"bytes,1,rep,name=icons,proto3" json:"icons,omitempty"`
}

func (x *GetIconsResponse) Reset() {
	*x = GetIconsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIconsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIconsResponse) ProtoMessage() {}

func (x *GetIconsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIconsResponse.ProtoReflect.Descriptor instead.
func (*GetIconsResponse) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetIconsResponse) GetIcons() []*Icon {
	if x != nil {
		return x.Icons
	}
	return nil
}

type GetEmojiIconsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetEmojiIconsRequest) Reset() {
	*x = GetEmojiIconsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmojiIconsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmojiIconsRequest) ProtoMessage() {}

func (x *GetEmojiIconsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmojiIconsRequest.ProtoReflect.Descriptor instead.
func (*GetEmojiIconsRequest) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{5}
}

type GetEmojiIconsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Icons []*Icon `protobuf:"bytes,1,rep,name=icons,proto3" json:"icons,omitempty"`
}

func (x *GetEmojiIconsResponse) Reset() {
	*x = GetEmojiIconsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmojiIconsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmojiIconsResponse) ProtoMessage() {}

func (x *GetEmojiIconsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmojiIconsResponse.ProtoReflect.Descriptor instead.
func (*GetEmojiIconsResponse) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetEmojiIconsResponse) GetIcons() []*Icon {
	if x != nil {
		return x.Icons
	}
	return nil
}

type DeleteIconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OwnerUuid string `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
}

func (x *DeleteIconRequest) Reset() {
	*x = DeleteIconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIconRequest) ProtoMessage() {}

func (x *DeleteIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIconRequest.ProtoReflect.Descriptor instead.
func (*DeleteIconRequest) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteIconRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DeleteIconRequest) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

type DeleteIconResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteIconResponse) Reset() {
	*x = DeleteIconResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIconResponse) ProtoMessage() {}

func (x *DeleteIconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIconResponse.ProtoReflect.Descriptor instead.
func (*DeleteIconResponse) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{8}
}

type UploadIconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*UploadIconRequest_Info
	//	*UploadIconRequest_ChunkData
	Data isUploadIconRequest_Data `protobuf_oneof:"data"`
}

func (x *UploadIconRequest) Reset() {
	*x = UploadIconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadIconRequest) ProtoMessage() {}

func (x *UploadIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadIconRequest.ProtoReflect.Descriptor instead.
func (*UploadIconRequest) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{9}
}

func (m *UploadIconRequest) GetData() isUploadIconRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadIconRequest) GetInfo() *ImageInfo {
	if x, ok := x.GetData().(*UploadIconRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *UploadIconRequest) GetChunkData() []byte {
	if x, ok := x.GetData().(*UploadIconRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isUploadIconRequest_Data interface {
	isUploadIconRequest_Data()
}

type UploadIconRequest_Info struct {
	Info *ImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadIconRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadIconRequest_Info) isUploadIconRequest_Data() {}

func (*UploadIconRequest_ChunkData) isUploadIconRequest_Data() {}

type UploadIconResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *UploadIconResponse) Reset() {
	*x = UploadIconResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadIconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadIconResponse) ProtoMessage() {}

func (x *UploadIconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadIconResponse.ProtoReflect.Descriptor instead.
func (*UploadIconResponse) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{10}
}

func (x *UploadIconResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *UploadIconResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ImageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kindof    string `protobuf:"bytes,1,opt,name=kindof,proto3" json:"kindof,omitempty"`
	OwnerUuid string `protobuf:"bytes,2,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{11}
}

func (x *ImageInfo) GetKindof() string {
	if x != nil {
		return x.Kindof
	}
	return ""
}

func (x *ImageInfo) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

type GetAvatarsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAvatarsRequest) Reset() {
	*x = GetAvatarsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvatarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarsRequest) ProtoMessage() {}

func (x *GetAvatarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarsRequest.ProtoReflect.Descriptor instead.
func (*GetAvatarsRequest) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{12}
}

type GetAvatarsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Icons []*Icon `protobuf:"bytes,1,rep,name=icons,proto3" json:"icons,omitempty"`
}

func (x *GetAvatarsResponse) Reset() {
	*x = GetAvatarsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_icon_v1_icon_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvatarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarsResponse) ProtoMessage() {}

func (x *GetAvatarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icon_v1_icon_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarsResponse.ProtoReflect.Descriptor instead.
func (*GetAvatarsResponse) Descriptor() ([]byte, []int) {
	return file_icon_v1_icon_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetAvatarsResponse) GetIcons() []*Icon {
	if x != nil {
		return x.Icons
	}
	return nil
}

var File_icon_v1_icon_service_proto protoreflect.FileDescriptor

var file_icon_v1_icon_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x63, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x69, 0x63,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x65, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e,
	0x6b, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x69, 0x6e, 0x64, 0x6f, 0x66, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x6e, 0x64, 0x6f, 0x66, 0x12, 0x1d, 0x0a,
	0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x22, 0x34, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x63,
	0x6f, 0x6e, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49,
	0x63, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x49, 0x63, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x05, 0x69, 0x63,
	0x6f, 0x6e, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x49,
	0x63, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x63, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x63,
	0x6f, 0x6e, 0x52, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x73, 0x22, 0x46, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x66, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x63, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x3c, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x42, 0x0a,
	0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x69,
	0x6e, 0x64, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x6e, 0x64,
	0x6f, 0x66, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05,
	0x69, 0x63, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x63,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x05, 0x69, 0x63, 0x6f, 0x6e,
	0x73, 0x32, 0xf6, 0x02, 0x0a, 0x0b, 0x49, 0x63, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x69,
	0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x41, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x2e,
	0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x6f, 0x6a, 0x69,
	0x49, 0x63, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x63, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x45, 0x6d, 0x6f, 0x6a, 0x69, 0x49, 0x63, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x49, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x2e,
	0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x63,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x69, 0x63, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x65, 0x74, 0x7a, 0x79, 0x31,
	0x2f, 0x63, 0x68, 0x61, 0x74, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x69, 0x63, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x63, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x69, 0x63, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_icon_v1_icon_service_proto_rawDescOnce sync.Once
	file_icon_v1_icon_service_proto_rawDescData = file_icon_v1_icon_service_proto_rawDesc
)

func file_icon_v1_icon_service_proto_rawDescGZIP() []byte {
	file_icon_v1_icon_service_proto_rawDescOnce.Do(func() {
		file_icon_v1_icon_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_icon_v1_icon_service_proto_rawDescData)
	})
	return file_icon_v1_icon_service_proto_rawDescData
}

var file_icon_v1_icon_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_icon_v1_icon_service_proto_goTypes = []interface{}{
	(*Icon)(nil),                  // 0: icon.v1.Icon
	(*GetIconRequest)(nil),        // 1: icon.v1.GetIconRequest
	(*GetIconResponse)(nil),       // 2: icon.v1.GetIconResponse
	(*GetIconsRequest)(nil),       // 3: icon.v1.GetIconsRequest
	(*GetIconsResponse)(nil),      // 4: icon.v1.GetIconsResponse
	(*GetEmojiIconsRequest)(nil),  // 5: icon.v1.GetEmojiIconsRequest
	(*GetEmojiIconsResponse)(nil), // 6: icon.v1.GetEmojiIconsResponse
	(*DeleteIconRequest)(nil),     // 7: icon.v1.DeleteIconRequest
	(*DeleteIconResponse)(nil),    // 8: icon.v1.DeleteIconResponse
	(*UploadIconRequest)(nil),     // 9: icon.v1.UploadIconRequest
	(*UploadIconResponse)(nil),    // 10: icon.v1.UploadIconResponse
	(*ImageInfo)(nil),             // 11: icon.v1.ImageInfo
	(*GetAvatarsRequest)(nil),     // 12: icon.v1.GetAvatarsRequest
	(*GetAvatarsResponse)(nil),    // 13: icon.v1.GetAvatarsResponse
}
var file_icon_v1_icon_service_proto_depIdxs = []int32{
	0,  // 0: icon.v1.GetIconResponse.icon:type_name -> icon.v1.Icon
	0,  // 1: icon.v1.GetIconsResponse.icons:type_name -> icon.v1.Icon
	0,  // 2: icon.v1.GetEmojiIconsResponse.icons:type_name -> icon.v1.Icon
	11, // 3: icon.v1.UploadIconRequest.info:type_name -> icon.v1.ImageInfo
	0,  // 4: icon.v1.GetAvatarsResponse.icons:type_name -> icon.v1.Icon
	1,  // 5: icon.v1.IconService.GetIcon:input_type -> icon.v1.GetIconRequest
	3,  // 6: icon.v1.IconService.GetIcons:input_type -> icon.v1.GetIconsRequest
	5,  // 7: icon.v1.IconService.GetEmojiIcons:input_type -> icon.v1.GetEmojiIconsRequest
	7,  // 8: icon.v1.IconService.DeleteIcon:input_type -> icon.v1.DeleteIconRequest
	9,  // 9: icon.v1.IconService.UploadIcon:input_type -> icon.v1.UploadIconRequest
	2,  // 10: icon.v1.IconService.GetIcon:output_type -> icon.v1.GetIconResponse
	4,  // 11: icon.v1.IconService.GetIcons:output_type -> icon.v1.GetIconsResponse
	6,  // 12: icon.v1.IconService.GetEmojiIcons:output_type -> icon.v1.GetEmojiIconsResponse
	8,  // 13: icon.v1.IconService.DeleteIcon:output_type -> icon.v1.DeleteIconResponse
	10, // 14: icon.v1.IconService.UploadIcon:output_type -> icon.v1.UploadIconResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_icon_v1_icon_service_proto_init() }
func file_icon_v1_icon_service_proto_init() {
	if File_icon_v1_icon_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_icon_v1_icon_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Icon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIconResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIconsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIconsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmojiIconsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmojiIconsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIconResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadIconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadIconResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvatarsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_icon_v1_icon_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvatarsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_icon_v1_icon_service_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*UploadIconRequest_Info)(nil),
		(*UploadIconRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_icon_v1_icon_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_icon_v1_icon_service_proto_goTypes,
		DependencyIndexes: file_icon_v1_icon_service_proto_depIdxs,
		MessageInfos:      file_icon_v1_icon_service_proto_msgTypes,
	}.Build()
	File_icon_v1_icon_service_proto = out.File
	file_icon_v1_icon_service_proto_rawDesc = nil
	file_icon_v1_icon_service_proto_goTypes = nil
	file_icon_v1_icon_service_proto_depIdxs = nil
}
